"use client";
import { useEffect, useState } from "react";
import { Archive, Coins, Sword, Shield, Sparkles, Map as MapIcon, KeyRound, Gem, FlaskConical, ShoppingBag, BookOpen, Crown, LockKeyhole, Tent, Check, Target, Users, ChevronLeft, ChevronRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { AlertDialog, AlertDialogContent, AlertDialogHeader, AlertDialogTitle, AlertDialogDescription, AlertDialogFooter, AlertDialogCancel, AlertDialogAction } from "@/components/ui/alert-dialog";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { ToggleGroup, ToggleGroupItem } from "@/components/ui/toggle-group";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Progress } from "@/components/ui/progress";
import { ITEMS, SLOT_NAMES, RARITY_NAMES, SPECIALIZATIONS, SPECIALIZATION_BRANCHES, REGIONS, CLASSES, CLASSIC_CLASSES, RACES, RACE_TREES, RACIAL_PATH_NAMES, CLASS_TECHNIQUES, HERO_STORIES, JOURNEY_OPTIONS, JOURNEY_CHOICES, heroRace, shop, seasonDay, seasonBoss, talentPoints, racialPoints, storyProgress, trainingPlan, available, activeJourney, PATH_NAMES, TACTICS, availableAbilities, abilityCooldownRemaining, type HeroClass, type Action, type Campaign, type ChestItem, type Hero, type TalentPath, type EvolutionBranch, type RacialPath, type JourneyDuration, type JourneyChoice, type AbilitySpec, type Battle, type BattleFighter, type Tactic } from "@/lib/game";
const fmt = (n: number) => n.toLocaleString("pt-BR");
type Controls = { state: Campaign; disabled: boolean; act: (action: Action) => void };
export function ItemIcon({ itemKey }: { itemKey: string }) {
  const d = ITEMS[itemKey];
  return <span className={"item-icon rarity-" + d?.rarity}><img src={"/items/" + itemKey + ".svg"} alt={d?.name ? "Imagem de " + d.name : "Item"} onError={e => { e.currentTarget.onerror = null; e.currentTarget.src = "/items/gemstone.svg"; }} /></span>;
}
export function EventPanel({ state, disabled, act }: Controls) {
  const [open, setOpen] = useState(false);
  const e = state.event; if (!e) return null;
  return <><section className="panel council-banner"><BookOpen /><div><span className="eyebrow">CONSELHO PENDENTE</span><strong>{e.title}</strong></div><Button variant="outline" disabled={disabled} onClick={() => setOpen(true)}>Decidir<ChevronRight /></Button></section><Dialog open={open} onOpenChange={setOpen}><DialogContent className="council-dialog"><DialogHeader><DialogTitle>{e.title}</DialogTitle><DialogDescription>{e.text}</DialogDescription></DialogHeader><div className="event-choices">{e.choices.map(c => <Button variant="outline" className="event-choice" key={c.id} disabled={disabled || state.gold < (c.cost || 0)} onClick={() => { act({ type: "event", eventId: e.id, choiceId: c.id }); setOpen(false); }}><strong>{c.label}</strong><span>{c.effect}</span>{state.gold < (c.cost || 0) && <small>Ouro insuficiente</small>}</Button>)}</div><p className="event-note">Resolva o pedido para avançar o dia. A escolha é salva imediatamente.</p></DialogContent></Dialog></>;
}
export function SeasonJourney({ state, disabled, selectBoss, selected }: { state: Campaign; disabled: boolean; selectBoss: (id: string) => void; selected: string }) {
  const boss = seasonBoss(state), beaten = state.bossSeasons.includes(state.season);
  return <section className="panel journey-panel"><div className="panel-heading"><div><span className="eyebrow">TERRITÓRIOS</span><h2>{REGIONS[state.region - 1]}</h2></div><MapIcon /></div><div className="region-list">{REGIONS.map((name, i) => <span key={name} data-unlocked={i < state.region}>{i < state.region ? <Check /> : <LockKeyhole />}{name}</span>)}</div><div className="season-boss"><span className="eyebrow">CHEFE DA TEMPORADA</span>{beaten ? <><h3>Desafio vencido</h3><p>O equipamento está no baú. O próximo chefe chega na nova temporada.</p></> : boss ? <><h3>{boss.title}</h3><p>{boss.description}</p><p className="boss-reward">+{boss.reward} ouro · +45 renome<br />Equipamento épico + Chave Antiga</p><Button variant={selected === boss.id ? "default" : "outline"} disabled={disabled} onClick={() => selectBoss(boss.id)}><Crown />{selected === boss.id ? "Chefe selecionado" : "Preparar confronto"}</Button></> : <><h3>Prepare sua equipe</h3><p>O chefe fica disponível entre os dias 21 e 28. Faltam {21 - seasonDay(state)} dias.</p></>}</div></section>;
}
export function SpecializationPanel({ hero, disabled, act }: { hero: Hero; disabled: boolean; act: (action: Action) => void }) {
  const points = talentPoints(hero), paths = ["offense", "healing", "defense"] as TalentPath[];
  return <section className="talent-panel"><div><h3>Árvore de evolução ramificada</h3><span>{points} ponto{points === 1 ? "" : "s"}</span></div><p>Nível 4: escolha o caminho principal. Nível 7: escolha uma ramificação. Nível 10: transforme a ramificação em Ultimate. As escolhas são permanentes.</p><Tabs defaultValue={hero.talent?.path || "offense"} className="talent-tabs"><TabsList aria-label="Caminhos da evolução">{paths.map(path => <TabsTrigger value={path} key={path}>{PATH_NAMES[path]}</TabsTrigger>)}</TabsList>{paths.map(path => {
    const spec = SPECIALIZATIONS[hero.class][path], chosen = hero.talent?.path === path, rank = chosen ? hero.talent!.rank : 0, otherPath = !!hero.talent && !chosen;
    const branches = SPECIALIZATION_BRANCHES[hero.class][path];
    return <TabsContent value={path} key={path}><div className="tree-branch-heading"><span className="eyebrow">{CLASSES[hero.class].name} · {PATH_NAMES[path]}</span><h4>{spec.name}</h4><p>{spec.description}</p></div>
      <div className="branch-stage stage-root" data-learnt={chosen}><div className="tree-node">{chosen ? <Check /> : "4"}</div><div><strong>{spec.stages[0]}</strong><span>Nível 4 · escolha do caminho principal</span></div><Button size="sm" variant={chosen ? "ghost" : "outline"} disabled={disabled || chosen || otherPath || points === 0} onClick={() => act({ type: "specialize", heroId: hero.id, path })}>{chosen ? "Escolhido" : otherPath ? "Outro caminho" : points === 0 ? "Nv. 4" : "Escolher"}</Button></div>
      <div className="branch-split" aria-label="Ramificações do nível 7">{(["a", "b"] as EvolutionBranch[]).map(branchId => { const branch = branches[branchId], branchChosen = chosen && hero.talent?.branch === branchId, branchBlocked = otherPath || !chosen || !!hero.talent?.branch && !branchChosen; return <section className="branch-card" key={branchId} data-chosen={branchChosen}><div className="branch-card-top"><span className="tree-node">{branchChosen && rank >= 2 ? <Check /> : "7"}</span><div><strong>{branch.name}</strong><small>{branch.style === "execution" ? "Alvo único" : branch.style === "storm" ? "Área" : branch.style === "lifebloom" ? "Cura focada" : branch.style === "sanctuary" ? "Proteção coletiva" : branch.style === "fortress" ? "Tanque" : "Controle"}</small></div></div><p>{branch.description}</p><Button size="sm" variant={branchChosen ? "ghost" : "outline"} disabled={disabled || rank >= 2 || branchBlocked || points === 0} onClick={() => act({ type: "specialize", heroId: hero.id, path, branch: branchId })}>{branchChosen && rank >= 2 ? "Ativa" : branchBlocked ? chosen ? "Outra ramificação" : "Escolha o caminho no Nv. 4" : points === 0 ? "Nv. 7" : "Escolher ramificação"}</Button>
        <div className="ultimate-node" data-unlocked={branchChosen && rank >= 3}><span className="tree-node">{branchChosen && rank >= 3 ? <Crown /> : "10"}</span><div><strong>{branch.stage3}</strong><small>Ultimate · habilidade evoluída +25% mais forte</small></div>{branchChosen && <Button size="sm" variant={rank >= 3 ? "ghost" : "outline"} disabled={disabled || rank !== 2 || points === 0} onClick={() => act({ type: "specialize", heroId: hero.id, path, branch: branchId })}>{rank >= 3 ? "Ultimate" : points === 0 ? "Nv. 10" : "Dominar"}</Button>}</div>
      </section>; })}</div>
      {hero.talent && <p className="tree-choice-note">Evolução atual: {SPECIALIZATIONS[hero.class][hero.talent.path].name}{hero.talent.branch ? " → " + SPECIALIZATION_BRANCHES[hero.class][hero.talent.path][hero.talent.branch].name : ""} · grau {hero.talent.rank}.</p>}
    </TabsContent>;
  })}</Tabs></section>;
}
export function RaceEvolutionPanel({ hero, disabled, act }: { hero: Hero; disabled: boolean; act: (action: Action) => void }) {
  const race = heroRace(hero), paths = ["heritage", "spirit", "war"] as RacialPath[], points = racialPoints(hero), technique = CLASS_TECHNIQUES[hero.class];
  return <section className="racial-panel"><div className="racial-heading"><div><span className="eyebrow">EVOLUÇÃO RACIAL · {RACES[race].name}</span><h3>Árvore racial</h3></div><span>{points} ponto{points === 1 ? "" : "s"}</span></div><p>Escolha um dos três caminhos da raça. As etapas liberam nos níveis 3, 6 e 9 e a escolha é permanente.</p><div className="class-technique"><Sparkles /><div><strong>{CLASS_TECHNIQUES[hero.class].name}</strong><span>{technique.description}</span></div></div><div className="racial-grid">{paths.map(path => { const spec = RACE_TREES[race][path], chosen = hero.racial?.path === path, rank = chosen ? hero.racial!.rank : 0, blocked = !!hero.racial && !chosen; const required = rank === 0 ? 3 : rank === 1 ? 6 : 9; return <section className="racial-card" key={path} data-chosen={chosen}><span className="eyebrow">{RACIAL_PATH_NAMES[path]}</span><h4>{rank >= 3 ? spec.stage3 : rank >= 2 ? spec.stage2 : spec.name}</h4><p>{spec.description}</p><div className="racial-ability"><Sparkles /><span><strong>{spec.ability.name}</strong><small>{spec.ability.description}</small></span></div><Button size="sm" variant={chosen ? "default" : "outline"} disabled={disabled || blocked || rank >= 3 || points === 0} onClick={() => act({ type: "racial-specialize", heroId: hero.id, path })}>{blocked ? "Outro caminho escolhido" : rank >= 3 ? "Dominada" : points === 0 ? "Nv. " + required : rank === 0 ? "Escolher caminho" : rank === 1 ? "Evoluir · Nv. 6" : "Dominar · Nv. 9"}</Button></section>; })}</div></section>;
}
export function HeroStoryPanel({ state, hero, disabled, act }: Controls & { hero: Hero }) {
  const spec = HERO_STORIES[hero.class], progress = storyProgress(hero), stage = hero.storyStage || 0, traveling = !!activeJourney(state, hero.id);
  const levelOk = stage === 0 || stage === 1 && hero.level >= 4 || stage === 2 && hero.level >= 7, energyOk = stage < 2 ? hero.energy >= 25 : hero.energy >= 40, goldOk = state.gold >= progress.cost;
  return <section className="story-panel"><div className="story-heading"><div><span className="eyebrow">HISTÓRIA PESSOAL</span><h3>{spec.title}</h3></div><span>{stage}/3</span></div><p>{spec.synopsis}</p><div className="story-steps">{spec.stages.map((name, i) => <span key={name} data-done={stage > i}><strong>{i + 1}</strong>{name}</span>)}</div>{hero.storyAbilityUnlocked ? <div className="story-unlocked"><Crown /><div><strong>{spec.ability.name}</strong><span>{spec.ability.description}</span></div></div> : <><div className="story-next"><strong>Próximo: {progress.label}</strong><span>{progress.requirement}{progress.cost ? " · " + progress.cost + " ouro" : ""} · −{progress.energy} energia</span></div><Button variant="outline" disabled={disabled || traveling || !available(hero, state) || !levelOk || !energyOk || !goldOk} onClick={() => act({ type: "story-step", heroId: hero.id })}><BookOpen />Avançar história</Button>{traveling && <small className="muted">O herói está viajando.</small>}{!levelOk && <small className="muted">A próxima etapa ainda exige mais nível.</small>}</>}</section>;
}
export function JourneyPanel({ state, disabled, act }: Controls) {
  const candidates = state.heroes.filter(h => available(h, state));
  const [heroId, setHeroId] = useState(candidates[0]?.id || ""), [duration, setDuration] = useState<JourneyDuration>(3);
  useEffect(() => { if (!candidates.some(h => h.id === heroId)) setHeroId(candidates[0]?.id || ""); }, [state.day, state.journeys.length, state.heroes.length, heroId]);
  return <section className="panel journey-training-panel"><div className="panel-heading"><div><h2>Viagens de desenvolvimento</h2><p>Envie um herói por 3, 5 ou 7 dias. Ele ganha XP diariamente e a sede continua funcionando.</p></div><MapIcon /></div>{state.journeys.length > 0 && <div className="active-journeys">{state.journeys.map(j => { const h = state.heroes.find(hero => hero.id === j.heroId); if (!h) return null; return <section key={j.id}><div className="journey-row"><div><strong>{h.name}</strong><span>{RACES[heroRace(h)].name} · {j.remaining} dia{j.remaining === 1 ? "" : "s"} restante{j.remaining === 1 ? "" : "s"} · +{j.xpEarned} XP</span></div><span className="subtle-chip">{j.duration} dias</span></div><ToggleGroup type="single" value={j.choice} onValueChange={v => { if (v) act({ type: "journey-choice", journeyId: j.id, choice: v as JourneyChoice }); }} variant="outline" disabled={disabled} aria-label={"Decisão da viagem de " + h.name}>{(Object.keys(JOURNEY_CHOICES) as JourneyChoice[]).map(choice => <ToggleGroupItem key={choice} value={choice} title={JOURNEY_CHOICES[choice].description}>{JOURNEY_CHOICES[choice].name}</ToggleGroupItem>)}</ToggleGroup>{j.loot.length > 0 && <small className="positive">Saque encontrado: {j.loot.map(key => ITEMS[key]?.name || key).join(", ")}</small>}</section>; })}</div>}<div className="journey-start"><Select value={heroId} onValueChange={setHeroId}><SelectTrigger aria-label="Herói para viajar"><SelectValue placeholder="Escolha um herói" /></SelectTrigger><SelectContent>{candidates.map(h => <SelectItem value={h.id} key={h.id}>{h.name} · Nv. {h.level}</SelectItem>)}</SelectContent></Select><ToggleGroup type="single" value={String(duration)} onValueChange={v => { if (v) setDuration(Number(v) as JourneyDuration); }} variant="outline" aria-label="Duração da viagem">{([3,5,7] as JourneyDuration[]).map(days => <ToggleGroupItem key={days} value={String(days)}>{days} dias</ToggleGroupItem>)}</ToggleGroup><p>{JOURNEY_OPTIONS[duration].description} Base: +{JOURNEY_OPTIONS[duration].dailyXp} XP por dia, com bônus para iniciantes.</p><Button disabled={disabled || !!state.event || !heroId || candidates.length < 1 || state.heroes.filter(h => !activeJourney(state, h.id) && h.id !== heroId).length < 4} onClick={() => act({ type: "start-journey", heroId, duration })}><MapIcon />Enviar em viagem</Button></div></section>;
}

export function IndividualTraining({ state, hero, disabled, act }: Controls & { hero?: Hero }) {
  const [open, setOpen] = useState(false), [recipient, setRecipient] = useState(hero?.id || state.heroes.toSorted((a, b) => a.level - b.level)[0]?.id || "");
  const selected = state.heroes.find(h => h.id === recipient) || state.heroes[0], plan = trainingPlan(state, selected);
  return <><Button variant="outline" className="individual-training-trigger" disabled={disabled || !!state.event || state.gold < 90 || (hero ? !available(hero, state) : !state.heroes.some(h => available(h, state)))} onClick={() => { if (hero) setRecipient(hero.id); setOpen(true); }}><Target />Treino individual<span>{hero ? "+" + trainingPlan(state, hero).xp + " XP" : "90 ouro"}</span></Button><Dialog open={open} onOpenChange={setOpen}><DialogContent className="training-dialog"><DialogHeader><DialogTitle>Treinamento individual</DialogTitle><DialogDescription>Escolha um herói para receber atenção exclusiva. O treino avança um dia e os demais recuperam energia.</DialogDescription></DialogHeader><RadioGroup className="individual-candidates" value={selected.id} onValueChange={setRecipient} aria-label="Herói para treinar">{state.heroes.map(h => <label className="equip-recipient" key={h.id} htmlFor={"train-" + h.id}><RadioGroupItem id={"train-" + h.id} value={h.id} disabled={!available(h, state)} /><span><strong>{h.name}</strong><small>{CLASSES[h.class].name} · Nv. {h.level} · {h.energy}% energia{h.injuredUntil > state.day ? " · Ferido" : ""}</small></span></label>)}</RadioGroup><div className="training-preview"><span><strong>+{plan.xp}</strong>XP</span><span><strong>{plan.cost}</strong>ouro</span><span><strong>−{plan.energy}</strong>energia</span></div><p className="catchup-note">{plan.catchup ? "Inclui +" + plan.catchup + " XP de recuperação por estar abaixo do nível dos companheiros." : "Recebe 90 XP de treino concentrado. Heróis de nível mais baixo recebem bônus para alcançar os companheiros."}</p><Button disabled={disabled || !!state.event || !available(selected, state) || state.gold < plan.cost} onClick={() => { act({ type: "train-hero", heroId: selected.id }); setOpen(false); }}><Target />Treinar {selected.name.split(" ")[0]} · {plan.cost} ouro</Button></DialogContent></Dialog></>;
}
export function ClassesGuide() {
  const [open, setOpen] = useState(false), [selected, setSelected] = useState<HeroClass>("warrior");
  const c = CLASSES[selected];
  return <><Button className="classes-guide-trigger" variant="outline" onClick={() => setOpen(true)}><Users />Ver as 7 classes clássicas</Button><Dialog open={open} onOpenChange={setOpen}><DialogContent className="classes-guide-dialog"><DialogHeader><DialogTitle>As 7 classes da guilda</DialogTitle><DialogDescription>Recrute uma classe diferente e use o treino individual para aproximar seu nível do restante da equipe.</DialogDescription></DialogHeader><Select value={selected} onValueChange={v => setSelected(v as HeroClass)}><SelectTrigger aria-label="Classe do compêndio"><SelectValue /></SelectTrigger><SelectContent>{CLASSIC_CLASSES.map(id => <SelectItem value={id} key={id}>{CLASSES[id].name}</SelectItem>)}</SelectContent></Select><section className="class-description"><span className="eyebrow">{c.role}</span><h3 style={{ color: c.color }}>{c.name}</h3><p>{c.description}</p></section><div className="class-paths">{(["offense", "healing", "defense"] as TalentPath[]).map(path => <section key={path}><strong>{PATH_NAMES[path]} · {SPECIALIZATIONS[selected][path].name}</strong><p>{SPECIALIZATIONS[selected][path].description}</p><small>Ramificações Nv. 7: {SPECIALIZATION_BRANCHES[selected][path].a.name} ou {SPECIALIZATION_BRANCHES[selected][path].b.name}</small></section>)}</div><p className="muted">Nível 4 escolhe o caminho principal; nível 7 abre dois subcaminhos; nível 10 transforma o subcaminho escolhido em Ultimate.</p></DialogContent></Dialog></>;
}
export function HeroEquipment({ state, hero, disabled, act }: Controls & { hero: Hero }) {
  return <section className="hero-equipment"><h3>Equipamentos</h3><div>{(["weapon", "offhand", "helmet", "armor", "gloves", "boots", "accessory"] as const).map(slot => {
    const item = state.chest.find(i => i.equippedTo === hero.id && ITEMS[i.key].slot === slot);
    return <div className="equipment-slot" key={slot}><span>{SLOT_NAMES[slot]}</span>{item ? <><strong>{ITEMS[item.key].name}</strong><small>{ITEMS[item.key].description}</small><Button size="sm" variant="ghost" disabled={disabled} onClick={() => act({ type: "unequip", itemId: item.id })}>Guardar no baú</Button></> : <strong className="muted">Sem equipamento</strong>}</div>;
  })}</div></section>;
}
export function ChestAndShop({ state, disabled, act }: Controls) {
  const [filter, setFilter] = useState("all"), [equip, setEquip] = useState<string | null>(null), [recipient, setRecipient] = useState(""), [sale, setSale] = useState<ChestItem | null>(null), [page, setPage] = useState(0);
  const [pageSize, setPageSize] = useState(16);
  useEffect(() => { const screen = window.matchMedia("(max-width: 760px)"), update = () => setPageSize(screen.matches ? 16 : 12); update(); screen.addEventListener("change", update); return () => screen.removeEventListener("change", update); }, []);
  const item = state.chest.find(i => i.id === equip);
  const equipSlots = ["weapon", "offhand", "helmet", "armor", "gloves", "boots", "accessory"];
  const chest = state.chest.filter(i => filter === "all" || filter === "equipment" && equipSlots.includes(ITEMS[i.key].slot) || filter === ITEMS[i.key].slot);
  const groups = new Map<string, { item: ChestItem; quantity: number }>();
  for (const i of chest) { const key = i.key + ":" + (i.equippedTo || "free"), existing = groups.get(key); if (existing) existing.quantity++; else groups.set(key, { item: i, quantity: 1 }); }
  const grouped = [...groups.values()], pages = Math.max(1, Math.ceil(grouped.length / pageSize)), currentPage = Math.min(page, pages - 1);
  const value = state.chest.filter(i => !i.equippedTo).reduce((n, i) => n + ITEMS[i.key].value, 0);
  function sell(i: ChestItem) { if (ITEMS[i.key].slot === "quest") setSale(i); else act({ type: "sell", itemId: i.id }); }
  return <><div className="section-heading"><div><span className="eyebrow">PATRIMÔNIO DA GUILDA</span><h2>Baú e mercador</h2><p>Um único baú para todos os heróis. Equipe o saque ou venda para financiar a campanha.</p></div><Archive /></div><div className="chest-summary"><span><Archive />{state.chest.length} itens</span><span><Coins />{fmt(value)} ouro em itens livres</span><span><FlaskConical />{state.chest.filter(i => i.key === "healing_potion").length} poções</span></div>
    <Tabs defaultValue="chest" className="inventory-tabs"><TabsList variant="line"><TabsTrigger value="chest"><Archive />Baú único</TabsTrigger><TabsTrigger value="shop"><ShoppingBag />Mercador</TabsTrigger></TabsList><TabsContent value="chest">
      <ToggleGroup type="single" value={filter} onValueChange={v => { if (v) { setFilter(v); setPage(0); } }} variant="outline" className="inventory-filter" aria-label="Filtrar itens do baú">{[["all", "Todos"], ["equipment", "Equipamentos"], ["material", "Materiais"], ["treasure", "Tesouros"], ["consumable", "Consumíveis"], ["quest", "Acesso"]].map(([id, label]) => <ToggleGroupItem value={id} key={id}>{label}</ToggleGroupItem>)}</ToggleGroup>
      {pages > 1 && <nav className="list-pagination inventory-pagination" aria-label="Páginas do baú"><Button variant="outline" disabled={currentPage === 0} aria-label="Página anterior do baú" onClick={() => setPage(currentPage - 1)}><ChevronLeft /></Button><span>{currentPage + 1} / {pages}</span><Button variant="outline" disabled={currentPage === pages - 1} aria-label="Próxima página do baú" onClick={() => setPage(currentPage + 1)}><ChevronRight /></Button></nav>}
      <div className="item-grid chest-grid">{grouped.slice(currentPage * pageSize, currentPage * pageSize + pageSize).map(({ item: i, quantity }) => {
        const d = ITEMS[i.key], owner = state.heroes.find(h => h.id === i.equippedTo), equippable = equipSlots.includes(d.slot);
        return <section key={i.id} className={"panel item-card rarity-border-" + d.rarity}><div className="item-card-top"><ItemIcon itemKey={i.key} /><span className={"rarity-text rarity-" + d.rarity}>{RARITY_NAMES[d.rarity]} · {SLOT_NAMES[d.slot]}{d.race ? " · " + RACES[d.race].name : ""}{quantity > 1 && <strong className="item-quantity">×{quantity} no baú</strong>}</span></div><h3>{d.name}</h3><p>{d.description}</p>{owner && <span className="item-owner"><Check />Equipado: {owner.name}</span>}<div className="item-actions">{equippable && (owner ? <Button variant="outline" disabled={disabled} onClick={() => act({ type: "unequip", itemId: i.id })}>Desequipar</Button> : <Button variant="outline" disabled={disabled} onClick={() => { setEquip(i.id); setRecipient(state.heroes.find(h => !d.race || heroRace(h) === d.race)?.id || state.heroes[0].id); }}>Equipar</Button>)}<Button variant="ghost" disabled={disabled || !!owner} onClick={() => sell(i)}><Coins />{quantity > 1 ? "Vender 1 · " : "Vender · "}{d.value}</Button></div></section>;
      })}</div>{chest.length === 0 && <div className="empty-state"><Archive /><h3>{filter === "all" ? "O baú está vazio" : "Nenhum item nesta categoria"}</h3><p>Vença expedições para encontrar equipamentos e tesouros. O mercador vende poções e itens básicos.</p></div>}
    </TabsContent><TabsContent value="shop"><div className="merchant-intro"><ShoppingBag /><div><h3>Mercador de Valen</h3><p>O preço de venda aparece em cada item do baú. Estoque de equipamentos renovado a cada sete dias.</p></div></div><div className="item-grid">{shop(state).map(offer => {
      const d = ITEMS[offer.key]; return <section className="panel item-card" key={offer.key}><div className="item-card-top"><ItemIcon itemKey={offer.key} /><span>{SLOT_NAMES[d.slot]}{d.race ? " · " + RACES[d.race].name : ""}</span></div><h3>{d.name}</h3><p>{d.description}</p>{offer.requiredFame > 0 && <span className="muted">Exige {offer.requiredFame} de renome</span>}<Button disabled={disabled || !offer.available || state.gold < offer.price || state.fame < offer.requiredFame} onClick={() => act({ type: "buy", key: offer.key })}><Coins />{offer.available ? "Comprar · " + offer.price + " ouro" : "Estoque esgotado"}</Button></section>;
    })}</div></TabsContent></Tabs>
    <Dialog open={!!item} onOpenChange={open => { if (!open) setEquip(null); }}><DialogContent className="equip-dialog">{item && <><DialogHeader><DialogTitle>Equipar {ITEMS[item.key].name}</DialogTitle><DialogDescription>{ITEMS[item.key].description} Substitui o item atual do mesmo espaço; o anterior fica no baú.</DialogDescription></DialogHeader><RadioGroup value={recipient} onValueChange={setRecipient} aria-label="Herói que receberá o equipamento">{state.heroes.map(h => { const def = ITEMS[item.key], compatible = (!def.race || heroRace(h) === def.race) && (!def.classes || def.classes.includes(h.class)) && (!def.levelReq || h.level >= def.levelReq); return <label key={h.id} className="equip-recipient" data-incompatible={!compatible} htmlFor={"equip-" + h.id}><RadioGroupItem id={"equip-" + h.id} value={h.id} disabled={!compatible} /><span><strong>{h.name}</strong><small>{CLASSES[h.class].name} · {RACES[heroRace(h)].name} · nível {h.level}{!compatible ? " · incompatível" : ""}</small></span></label>; })}</RadioGroup><Button disabled={disabled || !recipient || (() => { const h = state.heroes.find(h => h.id === recipient), d = ITEMS[item.key]; return !h || (!!d.race && heroRace(h) !== d.race) || (!!d.classes && !d.classes.includes(h.class)) || (!!d.levelReq && h.level < d.levelReq); })()} onClick={() => { act({ type: "equip", itemId: item.id, heroId: recipient }); setEquip(null); }}>Confirmar equipamento</Button></>}</DialogContent></Dialog>
    <AlertDialog open={!!sale} onOpenChange={open => { if (!open) setSale(null); }}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Vender item de acesso?</AlertDialogTitle><AlertDialogDescription>{sale && ITEMS[sale.key].name + " será removido do baú. Se for sua última unidade, a missão correspondente ficará bloqueada até conseguir outro. Você recebe " + ITEMS[sale.key].value + " ouro."}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Guardar item</AlertDialogCancel><AlertDialogAction onClick={() => { if (sale) act({ type: "sell", itemId: sale.id }); setSale(null); }}>Vender item</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </>;
}
export function BattleOrders({ battle, state, visibleFighters, disabled, act }: { battle: Battle; state: Campaign; visibleFighters: BattleFighter[]; disabled: boolean; act: (action: Action) => void }) {
  const [targeting, setTargeting] = useState<"healing_potion" | "antidote" | "stun_bomb" | null>(null);
  const [targetId, setTargetId] = useState("");
  const c = battle.combat; if (!c) return null;
  const hasPendingConsumable = !!c.pendingConsumable;

  const livingHeroes = c.fighters.filter(f => f.side === "hero" && f.hp > 0 && visibleFighters.some(v => v.id === f.id && v.hp > 0));
  const livingEnemies = c.fighters.filter(f => f.side === "enemy" && f.hp > 0 && visibleFighters.some(v => v.id === f.id && v.hp > 0));
  const wounded = livingHeroes.filter(f => f.hp < f.maxHp);
  const afflicted = livingHeroes.filter(f => (f.statuses || []).some(st => ["poison", "bleed", "vulnerable"].includes(st.kind)));
  const counts = {
    healing_potion: state.chest.filter(i => i.key === "healing_potion").length,
    antidote: state.chest.filter(i => i.key === "antidote").length,
    stun_bomb: state.chest.filter(i => i.key === "stun_bomb").length,
  };
  const targetOptions = targeting === "stun_bomb" ? livingEnemies : targeting === "antidote" ? afflicted : wounded;
  const descriptions = {
    healing_potion: "Recupera 70 PV de um herói ferido.",
    antidote: "Remove veneno, sangramento e vulnerabilidade.",
    stun_bomb: "Atordoa um inimigo e faz ele perder a próxima ação.",
  };
  function choose(key: "healing_potion" | "antidote" | "stun_bomb") {
    const options = key === "stun_bomb" ? livingEnemies : key === "antidote" ? afflicted : wounded;
    if (!counts[key] || hasPendingConsumable) return;
    setTargetId(options[0]?.id || "");
    setTargeting(key);
  }

  return <section className="battle-orders narrative-consumables">
    <div className="battle-consumables-heading"><div><span className="eyebrow">INTERVENÇÃO DA GUILDA</span><h3>Consumíveis</h3><p>Os heróis escolhem habilidades automaticamente. Durante a batalha você interfere apenas com itens.</p></div>{c.pendingConsumable && <span className="consumable-pending">Preparado para o próximo turno</span>}</div>
    <div className="combat-consumables-grid">
      <button type="button" className="combat-consumable combat-consumable-red" disabled={disabled || !counts.healing_potion || !!c.pendingConsumable || !wounded.length} onClick={() => choose("healing_potion")}>
        <ItemIcon itemKey="healing_potion" /><span><strong>Poção de Cura</strong><small>Recupera vida</small></span><b>×{counts.healing_potion}</b>
      </button>
      <button type="button" className="combat-consumable combat-consumable-green" disabled={disabled || !counts.antidote || !!c.pendingConsumable || !afflicted.length} onClick={() => choose("antidote")}>
        <ItemIcon itemKey="antidote" /><span><strong>Antídoto</strong><small>Remove efeitos nocivos</small></span><b>×{counts.antidote}</b>
      </button>
      <button type="button" className="combat-consumable combat-consumable-blue" disabled={disabled || !counts.stun_bomb || !!c.pendingConsumable || !livingEnemies.length} onClick={() => choose("stun_bomb")}>
        <ItemIcon itemKey="stun_bomb" /><span><strong>Bomba Atordoante</strong><small>Inimigo perde 1 ação</small></span><b>×{counts.stun_bomb}</b>
      </button>
    </div>
    <Button className="retreat-order" variant="ghost" disabled={disabled} onClick={() => act({ type: "battle-retreat" })}><Tent />Ordenar retirada · −{Math.min(state.fame, 3 + c.mission.rank * 2)} renome</Button>
    <Dialog open={!!targeting} onOpenChange={open => { if (!open) { setTargeting(null); setTargetId(""); } }}>
      <DialogContent className="ability-target-dialog consumable-target-dialog">
        <DialogHeader><DialogTitle>{targeting ? ITEMS[targeting].name : "Consumível"}</DialogTitle><DialogDescription>{targeting ? descriptions[targeting] : ""} Escolha o alvo.</DialogDescription></DialogHeader>
        <RadioGroup value={targetId} onValueChange={setTargetId} className="ability-target-list">
          {targetOptions.map(target => <label key={target.id} htmlFor={"consumable-target-" + target.id} className="ability-target"><RadioGroupItem id={"consumable-target-" + target.id} value={target.id} /><span><strong>{target.name}</strong><small>{target.hp}/{target.maxHp} PV{target.side === "hero" && target.statuses?.length ? " · " + target.statuses.map(st => st.kind).join(", ") : ""}</small></span></label>)}
        </RadioGroup>
        {!targetOptions.length && <p className="muted">Nenhum alvo válido neste momento.</p>}
        <Button disabled={!targeting || !targetId || disabled} onClick={() => { if (targeting && targetId) act({ type: "battle-consumable", key: targeting, targetId }); setTargeting(null); setTargetId(""); }}>Confirmar consumível</Button>
      </DialogContent>
    </Dialog>
  </section>;
}
