import assert from "node:assert/strict";
import fs from "node:fs";

const names = ["aric", "lyra", "doran", "kael", "elen", "sora", "pierro"];
for(const name of names){
  const module = fs.readFileSync("lib/portrait-art/" + name + ".ts", "utf8");
  const found = module.match(/data:image\/avif;base64,([A-Za-z0-9+/=]+)/);
  assert.ok(found, "Imagem não encontrada para " + name);
  const bytes = Buffer.from(found[1], "base64");
  assert.ok(bytes.length > 25000, "Imagem perdeu qualidade: " + name);
  assert.equal(bytes.subarray(4,12).toString("ascii"), "ftypavif", "AVIF inválido: " + name);
  const ispe = bytes.indexOf(Buffer.from("ispe"));
  assert.ok(ispe >= 0, "Dimensões AVIF ausentes: "+name);
  assert.equal(bytes.readUInt32BE(ispe + 8), 640, "Largura incorreta: "+name);
  assert.equal(bytes.readUInt32BE(ispe + 12), 800, "Altura incorreta: "+name);
}
const portraits = fs.readFileSync("lib/portraits.ts", "utf8");
for(const name of names)assert.ok(portraits.includes("portrait-art/"+name), "Retrato ausente: "+name);
assert.ok(portraits.includes('doran:"sora",kael:"kael",elen:"doran",sora:"elen"'), "Associação de Thorgar/Eldrin incorreta");
assert.ok(portraits.includes('bard:"pierro"'));
const heroPage = fs.readFileSync("app/game-client.tsx", "utf8");
assert.ok(heroPage.includes("portraitSource(hero.name"));
assert.ok(!heroPage.includes("portraitPosition("));
const styles = fs.readFileSync("app/ui.css", "utf8");
assert.ok(styles.includes("background-size:cover"));
assert.ok(styles.includes("background-size:150% auto"), "Miniaturas sem novo enquadramento");
assert.ok(styles.includes("height:265px"), "Retrato principal mobile não foi ampliado");
assert.ok(!styles.includes("hero-portraits-v6.webp"));
assert.ok(!fs.existsSync("public/hero-portraits-v6.webp"));
assert.ok(!fs.existsSync("public/hero-portraits-v121.webp"));
const merchant = fs.readFileSync("lib/portrait-art/merchant.ts", "utf8");
const merchantMatch = merchant.match(/base64,([A-Za-z0-9+/=]+)/);
assert.ok(merchantMatch,"Retrato do mercador ausente");
const merchantBytes = Buffer.from(merchantMatch[1],"base64");
assert.ok(merchantBytes.length > 50000,"Retrato do mercador perdeu nitidez");
assert.equal(merchantBytes.subarray(4,12).toString("ascii"),"ftypavif");
const merchantIspe = merchantBytes.indexOf(Buffer.from("ispe"));
assert.ok(merchantIspe >= 0,"Dimensões do mercador ausentes");
assert.equal(merchantBytes.readUInt32BE(merchantIspe + 8),640);
assert.equal(merchantBytes.readUInt32BE(merchantIspe + 12),640);
assert.ok(heroPage.includes('src={merchantPortrait}'),"A taverna não usa a arte nova");
assert.ok(!styles.includes('background:url("/reference/tavern-hero.webp") 94% 53%'),"O retrato improvisado antigo continua ativo");
console.log("Mercador: imagem HD 640x640 integrada e referência antiga removida.");
console.log("7 retratos novos presentes, íntegros e conectados. Imagens antigas removidas.");
