import assert from "node:assert/strict";
import fs from "node:fs";
import { applyAction, missions, newCampaign } from "../lib/game.ts";

const initial = newCampaign(20161009);
const mission = missions(initial)[0];
const started = applyAction(initial, {type:"mission",missionId:mission.id,team:initial.team,tactic:"balanced",expeditionSlot:1,startedAt:1_700_000_000_000});
const expedition = started.expeditions.find(e=>e.slot===1);
assert.ok(expedition && expedition.battle.status==="active" && expedition.battle.combat,"Missão de teste não iniciou");
const startingHP = new Map(expedition.battle.combat.fighters.map(f=>[f.id,f.hp]));
const complete = applyAction(started,{type:"battle-auto",expeditionId:expedition.id});
const finished = complete.expeditions.find(e=>e.id===expedition.id)?.battle;
assert.ok(finished,"Expedição desapareceu antes do resultado");
assert.notEqual(finished.status,"active");
assert.equal(finished.combat,undefined,"Motor ativo permaneceu após combate");
assert.ok(finished.fighters && finished.fighters.length >= 5,"Estado visual final dos combatentes não foi preservado");
assert.equal(new Set(finished.fighters.map(f=>f.id)).size,finished.fighters.length);
assert.ok(finished.fighters.some(f=>f.hp!==startingHP.get(f.id)),"A Arena voltou a mostrar o HP inicial em vez do resultado");
assert.ok(finished.fighters.every(f=>f.hp>=0 && f.hp<=f.maxHp),"Vida final inválida");
const before = fs.readFileSync("app/game-client.tsx","utf8");
const css = fs.readFileSync("app/ui.css","utf8");
assert.ok(before.includes('function CinematicBattlePage('));
assert.ok(before.includes('setCinematic(true)'));
assert.ok(before.includes('back={() => setCinematic(false)}'));
assert.ok(before.includes('type:"battle-auto",expeditionId:expedition.id}'));
assert.ok(before.includes('type:"battle-retreat",expeditionId:expedition.id}'));
assert.ok(before.includes('className="battle-stage"'),"Tela clássica removida");
assert.ok(css.includes(".cinema-arena {"));
assert.ok(css.includes("@media(prefers-reduced-motion:reduce)"));
console.log("Arena Cinematográfica: mantém motor, tela clássica e HP real no resultado.");
